# -*- coding: utf-8 -*-
"""ShodanwithCVSS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W-P3FzjZAHhR7-4F_of426xU6TFnjG38
"""

!pip install shodan

import shodan
import csv
API_KEY = KEY

api = shodan.Shodan(API_KEY)

limit = 1000  # Adjust if needed
results = api.search("has_vuln:true country:SN", limit=limit)

print(f"Found {results['total']} total results.")
print(f"Retrieved {len(results['matches'])} results.")

filename = "Senegal_shodan_vuln_with_cvss.csv"

with open(filename, mode="w", newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    # Column headers
    writer.writerow(["IP", "Port", "CVE", "CVSS", "Org", "Hostnames", "Location"])

    for match in results["matches"]:
        ip = match.get("ip_str", "")
        port = match.get("port", "")
        org = match.get("org", "n/a")
        hostnames = ", ".join(match.get("hostnames", [])) if "hostnames" in match else ""
        location = match.get("location", {}).get("city", "Unknown")

        # If vulnerabilities exist, loop through them
        if "vulns" in match:
            for cve, details in match["vulns"].items():
                cvss = details.get("cvss", "N/A") if isinstance(details, dict) else "N/A"
                writer.writerow([ip, port, cve, cvss, org, hostnames, location])
        else:
                      # No CVEs found for this machine
            writer.writerow([ip, port, "None", "N/A", org, hostnames, location])

print(f"✅ Data saved to {filename}")
from google.colab import files
files.download(filename)

